#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Mar 28 18:00:19 +08 2021
# SW Build 2729669 on Thu Dec  5 04:48:12 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim copy1_tb_behav -key {Behavioral:sim_1:Functional:copy1_tb} -tclbatch copy1_tb.tcl -log simulate.log"
xsim copy1_tb_behav -key {Behavioral:sim_1:Functional:copy1_tb} -tclbatch copy1_tb.tcl -log simulate.log

