#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Mar 17 22:55:45 +08 2021
# SW Build 2729669 on Thu Dec  5 04:48:12 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 3a5b9879a0ad435a9c27d101264c120d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot copy1_testbench_behav xil_defaultlib.copy1_testbench -log elaborate.log"
xelab -wto 3a5b9879a0ad435a9c27d101264c120d --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot copy1_testbench_behav xil_defaultlib.copy1_testbench -log elaborate.log

