#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Mar 17 23:05:20 +08 2021
# SW Build 2729669 on Thu Dec  5 04:48:12 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto f48616190f924c4bb11aec434947919a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot math_testbench_behav xil_defaultlib.math_testbench -log elaborate.log"
xelab -wto f48616190f924c4bb11aec434947919a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot math_testbench_behav xil_defaultlib.math_testbench -log elaborate.log

