webtalk_init -webtalk_dir /home/uros/sandbox/vivado/kernel_wrapper_ex/kernel_wrapper_ex.sim/sim_1/behav/xsim/xsim.dir/kernel_wrapper_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Jun 28 20:12:16 2020" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "66db7612-b22c-4e43-b345-4623cace2668" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1d33ac60795f4e7c883780593fe349be" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "16" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "unknown" -context "user_environment"
webtalk_add_data -client project -key os_release -value "unknown" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2979.757 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "206 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "135668_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2085039530 -regid "" -xml /home/uros/sandbox/vivado/kernel_wrapper_ex/kernel_wrapper_ex.sim/sim_1/behav/xsim/xsim.dir/kernel_wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/uros/sandbox/vivado/kernel_wrapper_ex/kernel_wrapper_ex.sim/sim_1/behav/xsim/xsim.dir/kernel_wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/uros/sandbox/vivado/kernel_wrapper_ex/kernel_wrapper_ex.sim/sim_1/behav/xsim/xsim.dir/kernel_wrapper_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
